<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\Core\RocketMQ.Core\RocketMQ.Core.csproj" />
      <ProjectReference Include="..\..\Transport\RocketMQ.Transport.Grpc\RocketMQ.Transport.Grpc.csproj" />
      <ProjectReference Include="..\..\Persistence\RocketMQ.Persistence.Wal\RocketMQ.Persistence.Wal.csproj" />
      <ProjectReference Include="..\..\Persistence\RocketMQ.Persistence.Sqlite\RocketMQ.Persistence.Sqlite.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
